<a href="https://colab.research.google.com/github/kabanyasu/safie-colab/blob/master/PL%E9%85%8D%E8%B3%A6%E3%82%B3%E3%83%BC%E3%83%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.simplefilter('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## PLのファイルまでディレクトリを移動させる

In [ ]:
cd /content/drive/MyDrive/1011_セーフィー株式会社/PL

/content/drive/.shortcut-targets-by-id/1TQ5vITu2g3s-9F2I1PirGz-g7baa9H92/1011_セーフィー株式会社/PL

## 読み込むファイルを指定する
- 以下のエクセルファイルのパスを指定する。
    - 〇月従業員一覧
    - 〇月個人コード順貼付データ
    - 〇月開発工数シート
    - マスタデータ
    - 全社費用配賦用GAS資料.xlsx

In [ ]:
#5月従業員一覧からメールアドレスと氏名を取得する
employee_excel = '入力データ格納場所/5月従業員一覧.xlsx'
#5月個人コード順貼付データから氏名と勤務時間を取得する
kintai_excel = '入力データ格納場所/5月個人コード順貼付データ.xlsx'
#5月開発工数シートからメールアドレス、工数を取得する
kousu_excel = '入力データ格納場所/5月開発工数シート.xlsx'
#マスタ（メールアドレスの漏れを防止）※過去のエクセルシートにしかない
master_excel = '入力データ格納場所/old/３月配賦基準算定 勤怠データ修正版.xlsx'

#PL
PL_excel = '入力データ格納場所/全社費用配賦用GAS資料.xlsx'

## 従業員一覧読み込み

In [ ]:
import pandas as pd
name_and_address = pd.read_excel(employee_excel)

##個人コード一覧読み込み

In [ ]:
category_name_hour = pd.read_excel(kintai_excel,
                                   header= None)

category_name_hour.head()

,0,1,2,3,4,5,6,7,8,9,...,351,352,353,354,355,356,357,358,359,360
0,部門名称,NaN,NaN,NaN,BU1営業部,BU1営業部,BU1営業部,BU1営業部,BU1営業部,BU1営業部,...,社長室,社長室,NaN,社長室,社長室,社長室,NaN,ESG推進室,ESG推進室,ESG推進室
1,NaN,合計,010000 第1BU,010100 第1BU営業部,20.0,22.0,42.0,52.0,65.0,74.0,...,188.0,333.0,339.0,501.0,502.0,503.0,100000 ESG推進室,100.0,337.0,338.0
2,NaN,【 計 329名 】,【 計 44名 】,【 計 27名 】,本多 桃子,村下 善恵,中根 ひとみ,永沢 篤,宮本 通世,岩渕 孝海,...,髙橋 由佳,西村 宣昭,白石 久也,工藤 克己,岡田 淳,岩田 彰一郎,【 計 3名 】,中内 陽子,松本 舞,宇治田 彩
3,出勤日数,5740.5,759.0,455.0,19.0,19.0,0.0,19.0,19.0,19.0,...,19.0,19.0,0.0,0.0,0.0,0.0,57.0,19.0,19.0,19.0
4,有休日数,407.5,53.0,26.5,3.0,0.0,0.0,1.0,2.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

## 開発工数シート読み込み

In [ ]:
man_hours_pivot = pd.read_excel(kousu_excel,
                                #上から3行は説明書きの部分なのでスキップする
                                skiprows   = 3)

man_hours_pivot.head()

,行ラベル,0:保守、運用,49:次世代カメラ開発(SafieOne）,52:解析PF,53:AIApp,61:Enterprise Toolマイグレーション,63:在庫システム,64:Entrance2,65:鹿島建設DX PJ,68:i-PRO製PTZ,...,78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool,79:(旧66)ソフトフェアPJ データ分析基盤,80:Pocket3,81:多台数対応,83:Pocket2+,84:メッシュWiFi,85:シェアプラス,86:Local Viewer,(空白),総計
0,a-baba@safie.jp,9488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9488.0
1,a-hirakawa@safie.jp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9960.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9960.0
2,a-ninomiya@safie.jp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9171.0
3,a-ohkawa@safie.jp,589.0,3119.0,NaN,3275.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10362.0
4,a-shimoyamada@safie.jp,9257.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9257.0

## PL科目、金額読み込み

In [ ]:
PL = pd.read_excel(PL_excel,sheet_name = 'PL',header = None)
PL.columns = ['PL科目','PL科目金額']

PL

     PL科目     PL科目金額
0      賞与        0.0
1   法定福利費  2266464.0
2   福利厚生費   267043.0
3     採用費  1343332.0
4   広告宣伝費        0.0
5    荷造運賃   536138.0
6     交際費   175575.0
7   旅費交通費   241439.0
8     通信費   800707.0
9    消耗品費  4075862.0
10  水道光熱費   798625.0
11    保険料   411113.0
12    修繕費    59497.0
13    研修費        0.0
14   地代家賃  8961834.0
15  支払手数料  9971422.0
16    諸会費     2833.0
17    会議費  2849910.0
18   租税公課  1753000.0
19   支払報酬        0.0
20  減価償却費  1385353.0
21     雑費   191552.0
22   為替差益        0.0
23    雑収入    50000.0
24   為替差損        0.0

## マスタ読み込み

In [ ]:
#※oldのファイルから読み込んでいるため、更新必要？
master = pd.read_excel(master_excel,
                       sheet_name = 'マスタ')

master.head()

,給与データ,従業員一覧,アドレス,Unnamed: 3,Unnamed: 4,部門,工数按分対象
0,寺本 明穂,坂本 明穂,a-sakamoto@safie.jp,NaN,NaN,BU1営業部,NaN
1,ﾃﾞﾌﾞﾘｯﾄ ﾆﾉﾐﾔｱﾘｿﾝ,二宮 アリソン,a-ninomiya@safie.jp,NaN,NaN,開発本部（49）,1.0
2,小嶋 幸恵,NaN,NaN,NaN,NaN,BU1プロダクト部,1.0
3,澤田 香菜,谷野 香菜,k-tanino@safie.jp,NaN,NaN,開発本部（65）,1.0
4,吉田 暁人,NaN,NaN,NaN,NaN,開発本部（64）,1.0

##従業員一覧から名前とメールアドレスを取得

In [ ]:
name_and_address = name_and_address[['氏名','メールアドレス']]

#半角・全角スペースが混同している可能性があるので、空白削除
name_and_address['氏名'] = name_and_address['氏名'].str.replace(' ', '')
name_and_address['氏名'] = name_and_address['氏名'].str.replace('　','')

name_and_address

        氏名                    メールアドレス
0    佐渡島隆平             sadox@safie.jp
1     下崎守朗              zksm@safie.jp
2     森本数馬           mkazuma@safie.jp
3     藤木麻那            manaty@safie.jp
4     横堀雅之               yok@safie.jp
..     ...                        ...
373    飯塚新        qc-staff01@safie.jp
374  水町佳奈子  mizumachi.kanako@safie.jp
375   長尾智子      nagao.tomoko@safie.jp
376   熊木美穂       kumaki.miho@safie.jp
377  大島麻美子     oshima.mamiko@safie.jp

[378 rows x 2 columns]

##マスタ読み込み

In [ ]:
master = master[['給与データ','アドレス']]

#縦結合する上でカラム名が一致していたほうが、キレイに出力されるので変更する
master.columns = ['氏名','メールアドレス']

#半角・全角スペースが混同している可能性があるので、空白削除
master['氏名'] = master['氏名'].str.replace(' ', '')
master['氏名'] = master['氏名'].str.replace('　','')

master.head()

                氏名              メールアドレス
0             寺本明穂  a-sakamoto@safie.jp
1  ﾃﾞﾌﾞﾘｯﾄﾆﾉﾐﾔｱﾘｿﾝ  a-ninomiya@safie.jp
2             小嶋幸恵                  NaN
3             澤田香菜    k-tanino@safie.jp
4             吉田暁人                  NaN

In [ ]:
name_and_address = pd.concat([name_and_address,master])
#重複削除
#後から結合ものを残したいので、keep=last
name_and_address = name_and_address.drop_duplicates(keep='last')
name_and_address = name_and_address.reset_index(drop = True,inplace = False)

name_and_address

        氏名             メールアドレス
0    佐渡島隆平      sadox@safie.jp
1     下崎守朗       zksm@safie.jp
2     森本数馬    mkazuma@safie.jp
3     藤木麻那     manaty@safie.jp
4     横堀雅之        yok@safie.jp
..     ...                 ...
408   石田諒子    r-saito@safie.jp
409   石山章子   n.suzuki@safie.jp
410   屋敷実咲  m-ohshima@safie.jp
411  斎藤永実果    e-nanbu@safie.jp
412   斉藤一貴    k-saito@safie.jp

[413 rows x 2 columns]

## 個人コード順貼付から部門名、時間、名前を取得

In [ ]:
#NaNの部分に、「氏名」を入れて、行の意味を持たせる
category_name_hour.loc[2][0] = '氏名'
category_name_hour.index     = category_name_hour[0]
category_name_hour           = category_name_hour.drop(0,axis=1)

In [ ]:
#必要な行のみを残す
category = category_name_hour.loc['部門名称']
name     = category_name_hour.loc['氏名']
hour     = category_name_hour.loc['出勤時間']

#縦表示させるため、転置する
category_name_hour = pd.DataFrame([category,name,hour]).T


#半角・全角スペースが混同している可能性があるので、空白削除
category_name_hour['氏名'] = category_name_hour['氏名'].str.replace(' ','')
category_name_hour['氏名'] = category_name_hour['氏名'].str.replace('　','')

category_name_hour

       部門名称       氏名                 出勤時間
1       NaN  【計329名】             51347:14
2       NaN   【計44名】  1900-10-14 09:26:00
3       NaN   【計27名】  1900-06-25 04:28:00
4    BU1営業部     本多桃子  1900-01-08 04:51:00
5    BU1営業部     村下善恵  1900-01-07 21:16:00
..      ...      ...                  ...
356     社長室    岩田彰一郎             00:00:00
357     NaN    【計3名】  1900-01-20 05:20:00
358  ESG推進室     中内陽子  1900-01-07 06:18:00
359  ESG推進室      松本舞  1900-01-06 12:25:00
360  ESG推進室     宇治田彩  1900-01-06 10:37:00

[360 rows x 3 columns]

In [ ]:
import datetime
attendance_time_list = list(category_name_hour['出勤時間'])
attendance_time_list

['51347:14',
 datetime.datetime(1900, 10, 14, 9, 26),
 datetime.datetime(1900, 6, 25, 4, 28),
 datetime.datetime(1900, 1, 8, 4, 51),
 datetime.datetime(1900, 1, 7, 21, 16),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 7, 0, 35),
 datetime.datetime(1900, 1, 6, 15, 3),
 datetime.datetime(1900, 1, 7, 1, 38),
 datetime.datetime(1900, 1, 7, 6, 4),
 datetime.datetime(1900, 1, 7, 4, 44),
 datetime.datetime(1900, 1, 7, 7, 33),
 datetime.datetime(1900, 1, 6, 18, 30),
 datetime.datetime(1900, 1, 9, 15, 34),
 datetime.datetime(1900, 1, 6, 15, 19),
 datetime.datetime(1900, 1, 7, 12, 0),
 datetime.datetime(1900, 1, 7, 6, 31),
 datetime.datetime(1900, 1, 7, 15, 6),
 datetime.datetime(1900, 1, 7, 11, 23),
 datetime.datetime(1900, 1, 7, 17, 28),
 datetime.datetime(1900, 1, 7, 3, 50),
 datetime.datetime(1900, 1, 7, 7, 10),
 datetime.datetime(1900, 1, 8, 2, 48),
 datetime.datetime(1900, 1, 8, 6, 26),
 datetime.datetime(1900, 1, 7, 8, 0),
 datetime.datetime(1900, 1, 6, 9, 57),
 datetime.datetime(1900, 1, 6, 23, 22),
 datetime.datetime(1900, 1, 6, 9, 20),
 datetime.time(0, 0),
 datetime.time(0, 0),
 datetime.datetime(1900, 4, 20, 4, 58),
 datetime.datetime(1900, 1, 5, 17, 34),
 datetime.datetime(1900, 1, 7, 0, 26),
 datetime.datetime(1900, 1, 7, 15, 3),
 datetime.datetime(1900, 1, 6, 8, 51),
 datetime.datetime(1900, 1, 6, 10, 43),
 datetime.datetime(1900, 1, 6, 11, 10),
 datetime.datetime(1900, 1, 7, 3, 24),
 datetime.datetime(1900, 1, 7, 11, 50),
 datetime.datetime(1900, 1, 6, 12, 52),
 datetime.datetime(1900, 1, 6, 23, 28),
 datetime.datetime(1900, 1, 7, 0, 36),
 datetime.datetime(1900, 1, 7, 2, 17),
 datetime.datetime(1900, 1, 7, 11, 52),
 datetime.datetime(1900, 1, 7, 22, 38),
 datetime.datetime(1900, 1, 6, 14, 58),
 datetime.datetime(1900, 1, 7, 5, 16),
 datetime.time(0, 0),
 datetime.datetime(1900, 10, 1, 19, 43),
 datetime.datetime(1900, 7, 19, 10, 20),
 datetime.datetime(1900, 1, 7, 20, 26),
 datetime.datetime(1900, 1, 7, 10, 56),
 datetime.datetime(1900, 1, 6, 22, 29),
 datetime.datetime(1900, 1, 7, 10, 11),
 datetime.datetime(1900, 1, 7, 1, 27),
 datetime.datetime(1900, 1, 8, 0, 41),
 datetime.datetime(1900, 1, 7, 4, 19),
 datetime.datetime(1900, 1, 8, 10, 32),
 datetime.datetime(1900, 1, 7, 19, 0),
 datetime.datetime(1900, 1, 7, 11, 22),
 datetime.datetime(1900, 1, 7, 11, 12),
 datetime.datetime(1900, 1, 7, 20, 18),
 datetime.datetime(1900, 1, 6, 15, 25),
 datetime.datetime(1900, 1, 8, 0, 31),
 datetime.datetime(1900, 1, 7, 22, 5),
 datetime.datetime(1900, 1, 7, 23, 42),
 datetime.datetime(1900, 1, 7, 4, 12),
 datetime.datetime(1900, 1, 7, 13, 40),
 datetime.datetime(1900, 1, 7, 12, 19),
 datetime.datetime(1900, 1, 7, 18, 32),
 datetime.datetime(1900, 1, 7, 4, 30),
 datetime.datetime(1900, 1, 7, 17, 25),
 datetime.datetime(1900, 1, 7, 2, 53),
 datetime.datetime(1900, 1, 6, 15, 10),
 datetime.datetime(1900, 1, 7, 2, 32),
 datetime.datetime(1900, 1, 6, 17, 49),
 datetime.datetime(1900, 1, 6, 14, 21),
 datetime.time(18, 21),
 datetime.datetime(1900, 3, 14, 9, 23),
 datetime.datetime(1900, 1, 5, 16, 52),
 datetime.datetime(1900, 1, 7, 12, 32),
 datetime.datetime(1900, 1, 6, 9, 48),
 datetime.datetime(1900, 1, 6, 14, 7),
 datetime.datetime(1900, 1, 6, 8, 0),
 datetime.datetime(1900, 1, 7, 13, 24),
 datetime.datetime(1900, 1, 5, 17, 3),
 datetime.datetime(1900, 1, 7, 9, 2),
 datetime.datetime(1900, 1, 7, 15, 26),
 datetime.datetime(1900, 1, 7, 5, 38),
 datetime.datetime(1900, 1, 6, 7, 31),
 datetime.time(0, 0),
 datetime.datetime(1900, 3, 25, 19, 48),
 datetime.datetime(1900, 2, 26, 1, 59),
 datetime.datetime(1900, 1, 7, 23, 46),
 datetime.datetime(1900, 1, 6, 11, 48),
 datetime.datetime(1900, 1, 6, 22, 13),
 datetime.datetime(1900, 1, 6, 8, 41),
 datetime.datetime(1900, 1, 7, 16, 23),
 datetime.datetime(1900, 1, 7, 9, 9),
 datetime.datetime(1900, 1, 7, 2, 7),
 datetime.datetime(1900, 1, 7, 3, 52),
 datetime.datetime(1900, 1, 28, 17, 49),
 datetime.datetime(1900, 1, 7, 10, 13),
 datetime.datetime(1900, 1, 7, 6, 42),
 datetime.datetime(1900, 1, 6, 19, 19),
 datetime.datetime(1900, 1, 7, 5, 35),
 datetime.datetime(1901, 1, 13, 0, 12),
 datetime.datetime(1900, 9, 17, 5, 17),
 datetime.datetime(1900, 1, 6, 4, 25),
 datetime.datetime(1900, 1, 6, 12, 34),
 datetime.datetime(1900, 1, 5, 23, 30),
 datetime.datetime(1900, 1, 6, 18, 13),
 datetime.datetime(1900, 1, 6, 10, 11),
 datetime.datetime(1900, 1, 6, 13, 24),
 datetime.datetime(1900, 1, 6, 1, 14),
 datetime.datetime(1900, 1, 6, 8, 9),
 datetime.datetime(1900, 1, 9, 0, 54),
 datetime.datetime(1900, 1, 8, 2, 7),
 datetime.datetime(1900, 1, 6, 21, 10),
 datetime.datetime(1900, 1, 6, 14, 43),
 datetime.datetime(1900, 1, 6, 16, 40),
 datetime.datetime(1900, 1, 7, 0, 27),
 datetime.datetime(1900, 1, 6, 14, 21),
 datetime.datetime(1900, 1, 6, 6, 31),
 datetime.datetime(1900, 1, 7, 4, 31),
 datetime.datetime(1900, 1, 7, 1, 32),
 datetime.datetime(1900, 1, 4, 21, 23),
 datetime.datetime(1900, 1, 7, 12, 8),
 datetime.datetime(1900, 1, 7, 20, 30),
 datetime.datetime(1900, 1, 7, 23, 9),
 datetime.datetime(1900, 1, 6, 18, 50),
 datetime.datetime(1900, 1, 7, 11, 1),
 datetime.datetime(1900, 1, 6, 21, 24),
 datetime.datetime(1900, 1, 6, 16, 15),
 datetime.datetime(1900, 1, 6, 23, 39),
 datetime.datetime(1900, 1, 7, 21, 8),
 datetime.datetime(1900, 1, 6, 23, 54),
 datetime.datetime(1900, 1, 7, 4, 58),
 datetime.datetime(1900, 1, 6, 19, 26),
 datetime.datetime(1900, 1, 6, 22, 0),
 datetime.datetime(1900, 1, 6, 12, 32),
 datetime.datetime(1900, 1, 6, 20, 0),
 datetime.datetime(1900, 1, 6, 21, 41),
 datetime.datetime(1900, 1, 6, 14, 54),
 datetime.datetime(1900, 1, 6, 22, 24),
 datetime.datetime(1900, 1, 6, 7, 25),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 20, 8, 11),
 datetime.datetime(1900, 1, 5, 5, 26),
 datetime.datetime(1900, 1, 6, 9, 56),
 datetime.datetime(1900, 1, 8, 16, 49),
 datetime.time(0, 0),
 datetime.datetime(1900, 3, 29, 12, 47),
 datetime.datetime(1900, 1, 7, 17, 27),
 datetime.datetime(1900, 1, 6, 13, 7),
 datetime.datetime(1900, 1, 5, 4, 18),
 datetime.datetime(1900, 1, 7, 7, 36),
 datetime.datetime(1900, 1, 6, 10, 17),
 datetime.datetime(1900, 1, 6, 14, 8),
 datetime.datetime(1900, 1, 7, 6, 3),
 datetime.datetime(1900, 1, 7, 6, 53),
 datetime.datetime(1900, 1, 7, 4, 42),
 datetime.datetime(1900, 1, 7, 11, 38),
 datetime.datetime(1900, 1, 6, 23, 29),
 datetime.datetime(1900, 1, 6, 15, 55),
 datetime.datetime(1900, 1, 6, 21, 14),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 7, 21, 57),
 datetime.datetime(1900, 1, 7, 21, 57),
 datetime.datetime(1901, 1, 8, 23, 30),
 datetime.datetime(1900, 1, 7, 5, 44),
 datetime.datetime(1900, 4, 4, 5, 38),
 datetime.datetime(1900, 1, 7, 7, 17),
 datetime.datetime(1900, 1, 6, 21, 5),
 datetime.datetime(1900, 1, 7, 9, 18),
 datetime.datetime(1900, 1, 7, 1, 47),
 datetime.datetime(1900, 1, 8, 0, 3),
 datetime.datetime(1900, 1, 7, 16, 44),
 datetime.datetime(1900, 1, 7, 11, 15),
 datetime.datetime(1900, 1, 7, 14, 58),
 datetime.datetime(1900, 1, 7, 14, 51),
 datetime.datetime(1900, 1, 7, 21, 18),
 datetime.datetime(1900, 1, 6, 19, 49),
 datetime.datetime(1900, 1, 6, 14, 43),
 datetime.datetime(1900, 1, 6, 20, 30),
 datetime.datetime(1900, 8, 2, 20, 40),
 datetime.datetime(1900, 1, 6, 20, 45),
 datetime.datetime(1900, 1, 6, 14, 10),
 datetime.datetime(1900, 1, 6, 12, 59),
 datetime.datetime(1900, 1, 6, 13, 41),
 datetime.datetime(1900, 1, 7, 19, 52),
 datetime.datetime(1900, 1, 7, 0, 35),
 datetime.datetime(1900, 1, 6, 21, 2),
 datetime.datetime(1900, 1, 6, 12, 37),
 datetime.datetime(1900, 1, 8, 4, 20),
 datetime.datetime(1900, 1, 7, 23, 53),
 datetime.datetime(1900, 1, 7, 8, 53),
 datetime.datetime(1900, 1, 6, 9, 0),
 datetime.datetime(1900, 1, 7, 0, 0),
 datetime.datetime(1900, 1, 8, 0, 20),
 datetime.datetime(1900, 1, 6, 13, 36),
 datetime.datetime(1900, 1, 6, 23, 5),
 datetime.datetime(1900, 1, 7, 14, 42),
 datetime.datetime(1900, 1, 7, 21, 51),
 datetime.datetime(1900, 1, 6, 19, 34),
 datetime.datetime(1900, 1, 6, 17, 29),
 datetime.datetime(1900, 1, 4, 21, 12),
 datetime.datetime(1900, 1, 6, 21, 3),
 datetime.datetime(1900, 1, 6, 17, 34),
 datetime.datetime(1900, 1, 7, 2, 49),
 datetime.datetime(1900, 1, 6, 17, 11),
 datetime.datetime(1900, 1, 7, 15, 40),
 datetime.datetime(1900, 1, 6, 22, 45),
 datetime.datetime(1900, 1, 6, 20, 2),
 datetime.time(16, 0),
 datetime.datetime(1900, 1, 6, 22, 56),
 datetime.datetime(1900, 1, 6, 13, 15),
 datetime.datetime(1900, 1, 1, 17, 12),
 datetime.time(2, 4),
 datetime.datetime(1900, 1, 3, 18, 33),
 datetime.datetime(1900, 2, 25, 15, 28),
 datetime.datetime(1900, 1, 7, 6, 21),
 datetime.datetime(1900, 1, 7, 8, 34),
 datetime.datetime(1900, 1, 6, 19, 8),
 datetime.datetime(1900, 1, 6, 19, 29),
 datetime.datetime(1900, 1, 7, 12, 26),
 datetime.datetime(1900, 1, 6, 10, 48),
 datetime.datetime(1900, 1, 6, 17, 44),
 datetime.datetime(1900, 1, 7, 16, 58),
 '10788:00',
 datetime.datetime(1900, 12, 13, 12, 3),
 datetime.datetime(1900, 1, 6, 20, 18),
 datetime.datetime(1900, 1, 5, 9, 43),
 datetime.datetime(1900, 1, 6, 23, 36),
 datetime.datetime(1900, 1, 7, 0, 50),
 datetime.datetime(1900, 1, 7, 10, 35),
 datetime.datetime(1900, 1, 7, 6, 44),
 datetime.datetime(1900, 1, 7, 12, 4),
 datetime.datetime(1900, 1, 7, 7, 10),
 datetime.datetime(1900, 1, 7, 7, 6),
 datetime.datetime(1900, 1, 7, 11, 6),
 datetime.datetime(1900, 1, 6, 9, 18),
 datetime.datetime(1900, 1, 8, 0, 0),
 datetime.datetime(1900, 1, 7, 4, 17),
 datetime.datetime(1900, 1, 7, 4, 3),
 datetime.datetime(1900, 1, 7, 8, 57),
 datetime.datetime(1900, 1, 7, 15, 27),
 datetime.datetime(1900, 1, 7, 5, 57),
 datetime.datetime(1900, 1, 7, 1, 23),
 datetime.datetime(1900, 1, 7, 13, 25),
 datetime.datetime(1900, 1, 7, 12, 54),
 datetime.datetime(1900, 1, 6, 8, 28),
 datetime.datetime(1900, 1, 6, 22, 16),
 datetime.datetime(1900, 1, 6, 23, 48),
 datetime.datetime(1900, 1, 6, 20, 28),
 datetime.datetime(1900, 1, 4, 20, 24),
 datetime.datetime(1900, 1, 8, 2, 38),
 datetime.datetime(1900, 1, 8, 3, 27),
 datetime.datetime(1900, 1, 7, 2, 22),
 datetime.datetime(1900, 1, 7, 5, 33),
 datetime.datetime(1900, 1, 7, 12, 16),
 datetime.datetime(1900, 1, 6, 20, 16),
 datetime.datetime(1900, 1, 7, 13, 32),
 datetime.datetime(1900, 1, 7, 8, 35),
 datetime.datetime(1900, 1, 7, 17, 56),
 datetime.datetime(1900, 1, 7, 9, 21),
 datetime.datetime(1900, 1, 7, 6, 4),
 datetime.datetime(1900, 1, 7, 21, 42),
 datetime.datetime(1900, 1, 6, 8, 21),
 datetime.datetime(1900, 1, 7, 4, 52),
 datetime.datetime(1900, 1, 6, 23, 29),
 datetime.datetime(1900, 1, 6, 21, 55),
 datetime.datetime(1900, 1, 7, 11, 59),
 datetime.datetime(1900, 1, 7, 3, 45),
 datetime.datetime(1900, 1, 6, 22, 29),
 datetime.datetime(1900, 1, 6, 18, 38),
 datetime.datetime(1900, 1, 6, 21, 54),
 datetime.datetime(1900, 1, 6, 16, 27),
 datetime.datetime(1900, 1, 6, 19, 50),
 datetime.datetime(1900, 1, 6, 10, 25),
 datetime.time(0, 0),
 datetime.time(0, 0),
 datetime.datetime(1900, 2, 9, 1, 1),
 datetime.datetime(1900, 1, 6, 12, 22),
 datetime.datetime(1900, 1, 7, 11, 33),
 datetime.datetime(1900, 1, 6, 10, 47),
 datetime.datetime(1900, 1, 6, 11, 35),
 datetime.datetime(1900, 1, 6, 8, 31),
 datetime.datetime(1900, 1, 6, 18, 13),
 datetime.datetime(1900, 2, 28, 22, 56),
 datetime.datetime(1900, 1, 6, 10, 24),
 datetime.datetime(1900, 1, 6, 7, 2),
 datetime.datetime(1900, 1, 6, 16, 42),
 datetime.datetime(1900, 1, 6, 9, 7),
 datetime.datetime(1900, 1, 7, 2, 2),
 datetime.datetime(1900, 1, 7, 12, 4),
 datetime.datetime(1900, 1, 7, 4, 17),
 datetime.datetime(1900, 1, 6, 19, 24),
 datetime.datetime(1900, 1, 6, 13, 54),
 datetime.datetime(1900, 8, 25, 14, 38),
 datetime.datetime(1900, 1, 5, 13, 10),
 datetime.datetime(1900, 5, 18, 6, 0),
 datetime.datetime(1900, 1, 6, 16, 49),
 datetime.datetime(1900, 1, 7, 4, 31),
 datetime.datetime(1900, 1, 7, 6, 21),
 datetime.datetime(1900, 1, 6, 14, 24),
 datetime.datetime(1900, 1, 7, 1, 2),
 datetime.datetime(1900, 1, 7, 5, 14),
 datetime.datetime(1900, 1, 6, 12, 27),
 datetime.datetime(1900, 1, 7, 5, 37),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 7, 17, 15),
 datetime.datetime(1900, 1, 7, 7, 10),
 datetime.datetime(1900, 1, 6, 8, 42),
 datetime.datetime(1900, 1, 7, 8, 33),
 datetime.datetime(1900, 1, 6, 22, 48),
 datetime.datetime(1900, 1, 7, 1, 20),
 datetime.datetime(1900, 1, 7, 0, 56),
 datetime.datetime(1900, 1, 7, 3, 46),
 datetime.datetime(1900, 1, 6, 18, 22),
 datetime.datetime(1900, 1, 6, 21, 54),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 3, 4, 59),
 datetime.datetime(1900, 1, 3, 22, 54),
 datetime.datetime(1900, 1, 2, 18, 0),
 datetime.datetime(1900, 1, 2, 22, 56),
 datetime.datetime(1900, 1, 29, 7, 59),
 datetime.datetime(1900, 1, 6, 8, 0),
 datetime.datetime(1900, 1, 8, 5, 58),
 datetime.datetime(1900, 1, 7, 21, 43),
 datetime.datetime(1900, 1, 6, 20, 18),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 26, 1, 46),
 datetime.datetime(1900, 1, 6, 19, 43),
 datetime.datetime(1900, 1, 6, 8, 21),
 datetime.datetime(1900, 1, 6, 10, 20),
 datetime.datetime(1900, 1, 6, 11, 22),
 datetime.datetime(1900, 2, 7, 9, 43),
 datetime.datetime(1900, 1, 7, 9, 44),
 datetime.datetime(1900, 1, 6, 22, 14),
 datetime.datetime(1900, 1, 8, 5, 49),
 datetime.datetime(1900, 1, 6, 20, 19),
 datetime.datetime(1900, 1, 7, 3, 29),
 datetime.time(23, 36),
 datetime.time(20, 32),
 datetime.datetime(1900, 1, 6, 13, 52),
 datetime.datetime(1900, 1, 6, 13, 52),
 datetime.datetime(1900, 1, 20, 12, 45),
 datetime.datetime(1900, 1, 5, 14, 38),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 7, 5, 18),
 datetime.datetime(1900, 1, 7, 16, 49),
 datetime.time(0, 0),
 datetime.time(0, 0),
 datetime.time(0, 0),
 datetime.time(0, 0),
 datetime.datetime(1900, 1, 20, 5, 20),
 datetime.datetime(1900, 1, 7, 6, 18),
 datetime.datetime(1900, 1, 6, 12, 25),
 datetime.datetime(1900, 1, 6, 10, 37)]

## 時間表記変更
- その都度修正する必要がある

In [ ]:
#出勤時間を秒数へ変換(数値検算済み)
import datetime
attendance_time_list = list(category_name_hour['出勤時間'])

second_list = []
#基準となる日時

#※その都度変更する必要がある
#シリアル値を日数へ変換すると、1900年1月1日を始点としている
#standard_date = datetime.datetime(1900,1,1)
standard_date = datetime.datetime(1899,12,31)

for time in attendance_time_list:
    try:
        #変換されている日時から、基準となる日時を差し引いて、求めたい時間のみを残す
        delta = time - standard_date
    except BaseException:
        second_list.append('NaN')
        continue
    second = delta.total_seconds()
    second = second/86400 #Excelは24時間=86400秒を1として計算しているから、こちらの処理でExcelで読み込めるようにする
    #閏年が関係している
    second_list.append(second)

# 表示したいときは以下をコメントアウトから戻す
#second_list

In [ ]:
category_name_hour['出勤時間'] = second_list
#category_name_hour

##category_name_hourにメールアドレス列を追加する

In [ ]:
category_name_hour_mail = pd.merge(category_name_hour,
                                   name_and_address,
                                   on='氏名',
                                   how='left')

print('結合に成功したのは、',str(len(category_name_hour_mail['メールアドレス'].dropna())),'件です。')

結合に成功したのは、 312 件です。

##工数ピボット貼付を読み込む

##工数ピボット貼付とcategory_name_hour_mailを結合して、工数別勤怠時間シートを再現する

In [ ]:
man_hours_attendance_time = pd.merge(category_name_hour_mail,
                                     man_hours_pivot,
                                     left_on  = 'メールアドレス',
                                     right_on = '行ラベル',
                                     how      = 'left')

In [ ]:
man_hours_attendance_time.to_excel('出力結果/勤怠時間シート.xlsx')

In [ ]:
# 漏れの件数を見る
#man_hours_pivotは総計行有り
#man_hours_attendance_timeは総計行無し

#空白と総計行を考慮して、-2を入れて調節する
count_more = len(man_hours_pivot)-2 - len(man_hours_attendance_time['行ラベル'].dropna())
print('工数ピボットからメールアドレスを結合できなかった人は' + str(count_more) + '人です')

工数ピボットからメールアドレスを結合できなかった人は0人です

##部門時間配賦の計算に必要な部分のみを取り出す

In [ ]:
#NaNだと処理できないので、半角スペースに変換
man_hours_attendance_time['行ラベル']= man_hours_attendance_time['行ラベル'].fillna(' ')

#行ラベルがある = 工数がある人
#行ラベルにメールアドレスのあるものを残して計算シートを作成する
department_allocation_calc = man_hours_attendance_time[man_hours_attendance_time['行ラベル'].str.endswith('.jp')]
department_allocation_calc.reset_index(drop = True,inplace = True)

#department_allocation_calc

##時間を部門配賦する

In [ ]:
#一単位当たりの時間を算出して新たな列として追加
department_allocation_calc['出勤時間/総計'] = department_allocation_calc['出勤時間'] / department_allocation_calc['総計']

department_allocation_calc

,部門名称,氏名,出勤時間,メールアドレス,行ラベル,0:保守、運用,49:次世代カメラ開発(SafieOne）,52:解析PF,53:AIApp,61:Enterprise Toolマイグレーション,...,79:(旧66)ソフトフェアPJ データ分析基盤,80:Pocket3,81:多台数対応,83:Pocket2+,84:メッシュWiFi,85:シェアプラス,86:Local Viewer,(空白),総計,出勤時間/総計
0,BU1プロダクト部,大友裕明,5.731944,otomo@safie.jp,otomo@safie.jp,4245.0,NaN,NaN,1681.0,NaN,...,NaN,NaN,1885.0,NaN,NaN,443.0,NaN,NaN,8254.0,0.000694
1,BU1プロダクト部,島田祐輝,7.018056,shimada@safie.jp,shimada@safie.jp,1131.0,1007.0,NaN,2082.0,NaN,...,NaN,NaN,453.0,NaN,NaN,NaN,NaN,NaN,10106.0,0.000694
2,デザインセンター,植松裕美,7.627083,y-uematsu@safie.jp,y-uematsu@safie.jp,8410.0,1245.0,NaN,1328.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10983.0,0.000694
3,BU1プロダクト部,ﾃﾞﾌﾞﾘｯﾄﾆﾉﾐﾔｱﾘｿﾝ,6.36875,a-ninomiya@safie.jp,a-ninomiya@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9171.0,0.000694
4,BU1プロダクト部,松田一輝,6.446528,k-matsuda@safie.jp,k-matsuda@safie.jp,2935.0,NaN,NaN,974.0,489.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9283.0,0.000694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,業務システム部,千葉洋隆,6.379861,y-chiba@safie.jp,y-chiba@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9187.0,0.000694
84,業務システム部,松山博樹,7.084722,h-matsuyama@safie.jp,h-matsuyama@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10202.0,0.000694
85,業務システム部,伊藤史仁,7.502778,f-ito@safie.jp,f-ito@safie.jp,2331.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10804.0,0.000694
86,業務システム部,吉川大樹,7.178472,t-yoshikawa@safie.jp,t-yoshikawa@safie.jp,2277.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10337.0,0.000694
87,業務システム部,菊池将太郎,6.808333,s-kikuchi@safie.jp,s-kikuchi@safie.jp,5093.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9804.0,0.000694

In [ ]:
import re

In [ ]:
department_allocation_calc.columns
#「\d」で数値が含まれているものを見つける
pj_list = [s for s in department_allocation_calc.columns if re.search(r'\d',s)]
pj_list

['0:保守、運用',
 '49:次世代カメラ開発(SafieOne）',
 '52:解析PF',
 '53:AIApp',
 '61:Enterprise Toolマイグレーション',
 '63:在庫システム',
 '64:Entrance2',
 '65:鹿島建設DX PJ',
 '68:i-PRO製PTZ',
 '69:MyPageと契約管理システム',
 '71:Pocket2 位置情報連携など機能追加/改良',
 '72:Safie API 組込販売改善',
 '73:SafieManagerV3',
 '74:MyPortal',
 '76:(旧59)ソフトフェアPJ Mobile App (2022)',
 '77:(旧60)ソフトフェアPJ Viewer (2022)',
 '78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool',
 '79:(旧66)ソフトフェアPJ データ分析基盤',
 '80:Pocket3',
 '81:多台数対応',
 '83:Pocket2+',
 '84:メッシュWiFi',
 '85:シェアプラス',
 '86:Local Viewer']

In [ ]:
#それぞれの部門に時間を配賦する
#部門の数が変動しやすいため、何かしら必要？
#正規表現で抽出してみる


pj_parcent_list = pd.DataFrame()

for pj_name in pj_list:
    pj_percent = department_allocation_calc[pj_name] * department_allocation_calc['出勤時間/総計']
    pj_parcent_list[pj_name] = pj_percent

In [ ]:
#部門、氏名などの情報を付与する
information = department_allocation_calc[['部門名称','氏名','出勤時間','メールアドレス']]

time_department_allocation_complete = pd.concat([information, pj_parcent_list], axis=1)

time_department_allocation_complete.head(4)

,部門名称,氏名,出勤時間,メールアドレス,0:保守、運用,49:次世代カメラ開発(SafieOne）,52:解析PF,53:AIApp,61:Enterprise Toolマイグレーション,63:在庫システム,...,76:(旧59)ソフトフェアPJ Mobile App (2022),77:(旧60)ソフトフェアPJ Viewer (2022),78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool,79:(旧66)ソフトフェアPJ データ分析基盤,80:Pocket3,81:多台数対応,83:Pocket2+,84:メッシュWiFi,85:シェアプラス,86:Local Viewer
0,BU1プロダクト部,大友裕明,5.731944,otomo@safie.jp,2.947917,NaN,NaN,1.167361,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.309028,NaN,NaN,0.307639,NaN
1,BU1プロダクト部,島田祐輝,7.018056,shimada@safie.jp,0.785417,0.699306,NaN,1.445833,NaN,NaN,...,0.790278,1.479167,0.789583,NaN,NaN,0.314583,NaN,NaN,NaN,NaN
2,デザインセンター,植松裕美,7.627083,y-uematsu@safie.jp,5.840278,0.864583,NaN,0.922222,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BU1プロダクト部,ﾃﾞﾌﾞﾘｯﾄﾆﾉﾐﾔｱﾘｿﾝ,6.36875,a-ninomiya@safie.jp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.36875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##部門時間を縦計し易い形で保存

In [ ]:
time_department_allocation_complete.to_excel('出力結果/時間部門配賦後.xlsx')

##PJ配賦時間縦計

In [ ]:
PJ = time_department_allocation_complete
PJ

,部門名称,氏名,出勤時間,メールアドレス,0:保守、運用,49:次世代カメラ開発(SafieOne）,52:解析PF,53:AIApp,61:Enterprise Toolマイグレーション,63:在庫システム,...,76:(旧59)ソフトフェアPJ Mobile App (2022),77:(旧60)ソフトフェアPJ Viewer (2022),78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool,79:(旧66)ソフトフェアPJ データ分析基盤,80:Pocket3,81:多台数対応,83:Pocket2+,84:メッシュWiFi,85:シェアプラス,86:Local Viewer
0,BU1プロダクト部,大友裕明,5.731944,otomo@safie.jp,2.947917,NaN,NaN,1.167361,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.309028,NaN,NaN,0.307639,NaN
1,BU1プロダクト部,島田祐輝,7.018056,shimada@safie.jp,0.785417,0.699306,NaN,1.445833,NaN,NaN,...,0.790278,1.479167,0.789583,NaN,NaN,0.314583,NaN,NaN,NaN,NaN
2,デザインセンター,植松裕美,7.627083,y-uematsu@safie.jp,5.840278,0.864583,NaN,0.922222,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BU1プロダクト部,ﾃﾞﾌﾞﾘｯﾄﾆﾉﾐﾔｱﾘｿﾝ,6.36875,a-ninomiya@safie.jp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.36875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BU1プロダクト部,松田一輝,6.446528,k-matsuda@safie.jp,2.038194,NaN,NaN,0.676389,0.339583,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,業務システム部,千葉洋隆,6.379861,y-chiba@safie.jp,NaN,NaN,NaN,NaN,NaN,6.379861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,業務システム部,松山博樹,7.084722,h-matsuyama@safie.jp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,業務システム部,伊藤史仁,7.502778,f-ito@safie.jp,1.61875,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,業務システム部,吉川大樹,7.178472,t-yoshikawa@safie.jp,1.58125,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,業務システム部,菊池将太郎,6.808333,s-kikuchi@safie.jp,3.536806,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pj_sum_list = []
for pj_name in pj_list:
    pj_sum = PJ[pj_name].sum()
    pj_sum_list.append(pj_sum)

pj_sum_list


df_pj_sum = pd.DataFrame([pj_list,pj_sum_list]).T

df_pj_sum.columns = ['部門名称','出勤時間']
df_pj_sum['データ種別'] = '配賦用PJ'

df_pj_sum

                                           部門名称        出勤時間  データ種別
0                                       0:保守、運用  219.553472  配賦用PJ
1                         49:次世代カメラ開発(SafieOne）   41.288194  配賦用PJ
2                                       52:解析PF   33.315972  配賦用PJ
3                                      53:AIApp   55.986806  配賦用PJ
4                    61:Enterprise Toolマイグレーション    2.026389  配賦用PJ
5                                     63:在庫システム    6.379861  配賦用PJ
6                                  64:Entrance2   33.851389  配賦用PJ
7                                  65:鹿島建設DX PJ    4.261111  配賦用PJ
8                                  68:i-PRO製PTZ    9.743056  配賦用PJ
9                            69:MyPageと契約管理システム   32.171528  配賦用PJ
10                   71:Pocket2 位置情報連携など機能追加/改良     15.9125  配賦用PJ
11                          72:Safie API 組込販売改善    9.193056  配賦用PJ
12                            73:SafieManagerV3   15.360417  配賦用PJ
13                                  74:MyPortal    5.646528  配賦用PJ
14           76:(旧59)ソフトフェアPJ Mobile App (2022)   23.647917  配賦用PJ
15               77:(旧60)ソフトフェアPJ Viewer (2022)   23.445139  配賦用PJ
16  78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool   13.527778  配賦用PJ
17                     79:(旧66)ソフトフェアPJ データ分析基盤    27.83125  配賦用PJ
18                                   80:Pocket3    3.695833  配賦用PJ
19                                     81:多台数対応   15.599306  配賦用PJ
20                                  83:Pocket2+     4.31875  配賦用PJ
21                                  84:メッシュWiFi     2.75625  配賦用PJ
22                                    85:シェアプラス      3.7625  配賦用PJ
23                              86:Local Viewer    5.552778  配賦用PJ

In [ ]:
df_pj_sum.to_excel('出力結果/PJ縦計データ.xlsx')

##Biz時間縦系計

In [ ]:
biz = pd.read_excel('出力結果/勤怠時間シート.xlsx')
biz

,Unnamed: 0,部門名称,氏名,出勤時間,メールアドレス,行ラベル,0:保守、運用,49:次世代カメラ開発(SafieOne）,52:解析PF,53:AIApp,...,78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool,79:(旧66)ソフトフェアPJ データ分析基盤,80:Pocket3,81:多台数対応,83:Pocket2+,84:メッシュWiFi,85:シェアプラス,86:Local Viewer,(空白),総計
0,0,NaN,【計329名】,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,【計44名】,287.393056,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,【計27名】,176.186111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,BU1営業部,本多桃子,8.202083,honda@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,BU1営業部,村下善恵,7.886111,murashita@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,355,社長室,岩田彰一郎,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,356,NaN,【計3名】,20.222222,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,357,ESG推進室,中内陽子,7.262500,y-nakauchi@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,358,ESG推進室,松本舞,6.517361,m-matsumoto@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,359,ESG推進室,宇治田彩,6.442361,a-ujita@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##biz部門ごとに縦計

In [ ]:
#部門名称の列にNaNが存在すると実行できないので半角スペースに変換しておく
biz['部門名称']= biz['部門名称'].fillna(' ')

biz_list = ['社長室',
            '経営企画部',
            '人事総務部',
            '経理部',
            '法務部',
            '内部監査室',
            'BU1営業部',
            'BU2営業部',
            'BU3営業部',
            'アライアンス戦略室',
            'マーケティング部',
            'カスタマーコミュニケーション部',
            '品質管理部',
            'ESG推進室']

biz_sum_list = []

for biz_name in biz_list:
    biz_vertical_sum_sheet = biz[biz["部門名称"].str.contains(biz_name)]
    biz_sum = biz_vertical_sum_sheet["出勤時間"].sum()
    biz_sum_list.append(biz_sum)

df_biz_sum = pd.DataFrame([biz_list,biz_sum_list]).T
df_biz_sum.columns = ['部門名称','出勤時間']

df_biz_sum['データ種別'] = '配賦用biz'

df_biz_sum

               部門名称        出勤時間   データ種別
0               社長室    20.53125  配賦用biz
1             経営企画部   42.114583  配賦用biz
2             人事総務部  132.093056  配賦用biz
3               経理部   36.489583  配賦用biz
4               法務部   26.073611  配賦用biz
5             内部監査室    6.577778  配賦用biz
6            BU1営業部  218.809028  配賦用biz
7            BU2営業部  200.195139  配賦用biz
8            BU3営業部   64.934028  配賦用biz
9         アライアンス戦略室   95.234722  配賦用biz
10         マーケティング部  222.808333  配賦用biz
11  カスタマーコミュニケーション部  349.334028  配賦用biz
12            品質管理部   46.390278  配賦用biz
13           ESG推進室   20.222222  配賦用biz

In [ ]:
df_biz_sum.to_excel('出力結果/biz縦計データ.xlsx')

##dev時間縦系計
- dev（保守・運用）は部門ごとに縦系する必要がある

In [ ]:
dev = pd.read_excel('出力結果/時間部門配賦後.xlsx')
dev

,Unnamed: 0,部門名称,氏名,出勤時間,メールアドレス,0:保守、運用,49:次世代カメラ開発(SafieOne）,52:解析PF,53:AIApp,61:Enterprise Toolマイグレーション,...,76:(旧59)ソフトフェアPJ Mobile App (2022),77:(旧60)ソフトフェアPJ Viewer (2022),78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool,79:(旧66)ソフトフェアPJ データ分析基盤,80:Pocket3,81:多台数対応,83:Pocket2+,84:メッシュWiFi,85:シェアプラス,86:Local Viewer
0,0,BU1プロダクト部,大友裕明,5.731944,otomo@safie.jp,2.947917,NaN,NaN,1.167361,NaN,...,NaN,NaN,NaN,NaN,NaN,1.309028,NaN,NaN,0.307639,NaN
1,1,BU1プロダクト部,島田祐輝,7.018056,shimada@safie.jp,0.785417,0.699306,NaN,1.445833,NaN,...,0.790278,1.479167,0.789583,NaN,NaN,0.314583,NaN,NaN,NaN,NaN
2,2,デザインセンター,植松裕美,7.627083,y-uematsu@safie.jp,5.840278,0.864583,NaN,0.922222,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,BU1プロダクト部,ﾃﾞﾌﾞﾘｯﾄﾆﾉﾐﾔｱﾘｿﾝ,6.368750,a-ninomiya@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,6.368750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,BU1プロダクト部,松田一輝,6.446528,k-matsuda@safie.jp,2.038194,NaN,NaN,0.676389,0.339583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,83,業務システム部,千葉洋隆,6.379861,y-chiba@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,84,業務システム部,松山博樹,7.084722,h-matsuyama@safie.jp,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,85,業務システム部,伊藤史仁,7.502778,f-ito@safie.jp,1.618750,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,86,業務システム部,吉川大樹,7.178472,t-yoshikawa@safie.jp,1.581250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,87,業務システム部,菊池将太郎,6.808333,s-kikuchi@safie.jp,3.536806,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##部門名称からdevのものを探し出し、抽出して縦計する

In [ ]:
#部門名称の列にNaNが存在すると実行できないので半角スペースに変換しておく
dev['部門名称']= dev['部門名称'].fillna(' ')


dev_list = ['BU1プロダクト部',
            'BU2プロダクト部',
            'BU3プロダクト部',
            'プロダクト基盤開発部',
            'プラットフォームビジネス開発室',
            'デザインセンター',
            '業務システム部']



dev_sum_list = []

for dev_name in dev_list:
    dev_vertical_sum_sheet = dev[dev['部門名称'].str.contains(dev_name)]
    dev_sum = dev_vertical_sum_sheet['0:保守、運用'].sum()
    dev_sum_list.append(dev_sum)

df_dev_sum = pd.DataFrame([dev_list,dev_sum_list]).T
df_dev_sum.columns = ['部門名称','出勤時間']
df_dev_sum['データ種別'] = '配賦用dev'

df_dev_sum

              部門名称       出勤時間   データ種別
0        BU1プロダクト部  25.183333  配賦用dev
1        BU2プロダクト部   20.95625  配賦用dev
2        BU3プロダクト部   8.235417  配賦用dev
3       プロダクト基盤開発部  73.516667  配賦用dev
4  プラットフォームビジネス開発室   6.413889  配賦用dev
5         デザインセンター  61.454167  配賦用dev
6          業務システム部  18.190278  配賦用dev

In [ ]:
df_dev_sum.to_excel('出力結果/dev縦計データ.xlsx')

##PLをbiz,dev,pjの合計で割ってそれぞれに配布する

In [ ]:
import pandas as pd
PL = pd.read_excel(PL_excel,sheet_name = 'PL',header = None)
PL.columns = ['PL科目','PL科目金額']

PL

     PL科目     PL科目金額
0      賞与        0.0
1   法定福利費  2266464.0
2   福利厚生費   267043.0
3     採用費  1343332.0
4   広告宣伝費        0.0
5    荷造運賃   536138.0
6     交際費   175575.0
7   旅費交通費   241439.0
8     通信費   800707.0
9    消耗品費  4075862.0
10  水道光熱費   798625.0
11    保険料   411113.0
12    修繕費    59497.0
13    研修費        0.0
14   地代家賃  8961834.0
15  支払手数料  9971422.0
16    諸会費     2833.0
17    会議費  2849910.0
18   租税公課  1753000.0
19   支払報酬        0.0
20  減価償却費  1385353.0
21     雑費   191552.0
22   為替差益        0.0
23    雑収入    50000.0
24   為替差損        0.0

##合計値算出

In [ ]:
PJ = df_pj_sum['出勤時間'].sum()
BIZ = df_biz_sum['出勤時間'].sum()
DEV = df_dev_sum['出勤時間'].sum()

all_sum = PJ + BIZ + DEV
all_sum

2304.585416666667

In [ ]:
PL_value_list = list(PL['PL科目金額'])
PL_value_list

PL_pj_list = []
PL_biz_list = []
PL_dev_list = []

for PL_value in PL_value_list:
    divide_category_value = PL_value / all_sum
    
    #それぞれの値で掛けて、リストに入れる
    PL_pj = divide_category_value * PJ
    PL_biz = divide_category_value * BIZ
    PL_dev = divide_category_value * DEV

    PL_pj_list.append(PL_pj)
    PL_biz_list.append(PL_biz)
    PL_dev_list.append(PL_dev)

##それぞれのリストにある数値を一か所にまとめる

In [ ]:
df_PL_divide_category = pd.DataFrame([PL_pj_list, PL_biz_list, PL_dev_list]).T

df_PL_divide_category.columns = ['配賦用Biz','配賦用dev','配賦用PJ']

df_PL_divide_category

          配賦用Biz        配賦用dev          配賦用PJ
0   0.000000e+00  0.000000e+00       0.000000
1   5.987568e+05  1.457296e+06  210410.935213
2   7.054770e+04  1.717039e+05   24791.378717
3   3.548828e+05  8.637387e+05  124710.448709
4   0.000000e+00  0.000000e+00       0.000000
5   1.416375e+05  3.447272e+05   49773.258249
6   4.638359e+04  1.128916e+05   16299.795607
7   6.378361e+04  1.552410e+05   22414.389016
8   2.115316e+05  5.148404e+05   74334.959082
9   1.076765e+06  2.620707e+06  378389.392120
10  2.109816e+05  5.135017e+05   74141.673168
11  1.086083e+05  2.643384e+05   38166.355525
12  1.571798e+04  3.825552e+04    5523.502430
13  0.000000e+00  0.000000e+00       0.000000
14  2.367547e+06  5.762301e+06  831986.686383
15  2.634261e+06  6.411448e+06  925713.458686
16  7.484249e+02  1.821569e+03     263.006242
17  7.528922e+05  1.832442e+06  264576.109911
18  4.631094e+05  1.127148e+06  162742.655268
19  0.000000e+00  0.000000e+00       0.000000
20  3.659840e+05  8.907575e+05  128611.537766
21  5.060441e+04  1.231645e+05   17783.046835
22  0.000000e+00  0.000000e+00       0.000000
23  1.320905e+04  3.214912e+04    4641.832723
24  0.000000e+00  0.000000e+00       0.000000

##PLシートの情報付与

In [ ]:
df_PL_divide_category_goal = pd.concat([PL,df_PL_divide_category],axis=1)
df_PL_divide_category_goal

     PL科目     PL科目金額        配賦用Biz        配賦用dev          配賦用PJ
0      賞与        0.0  0.000000e+00  0.000000e+00       0.000000
1   法定福利費  2266464.0  5.987568e+05  1.457296e+06  210410.935213
2   福利厚生費   267043.0  7.054770e+04  1.717039e+05   24791.378717
3     採用費  1343332.0  3.548828e+05  8.637387e+05  124710.448709
4   広告宣伝費        0.0  0.000000e+00  0.000000e+00       0.000000
5    荷造運賃   536138.0  1.416375e+05  3.447272e+05   49773.258249
6     交際費   175575.0  4.638359e+04  1.128916e+05   16299.795607
7   旅費交通費   241439.0  6.378361e+04  1.552410e+05   22414.389016
8     通信費   800707.0  2.115316e+05  5.148404e+05   74334.959082
9    消耗品費  4075862.0  1.076765e+06  2.620707e+06  378389.392120
10  水道光熱費   798625.0  2.109816e+05  5.135017e+05   74141.673168
11    保険料   411113.0  1.086083e+05  2.643384e+05   38166.355525
12    修繕費    59497.0  1.571798e+04  3.825552e+04    5523.502430
13    研修費        0.0  0.000000e+00  0.000000e+00       0.000000
14   地代家賃  8961834.0  2.367547e+06  5.762301e+06  831986.686383
15  支払手数料  9971422.0  2.634261e+06  6.411448e+06  925713.458686
16    諸会費     2833.0  7.484249e+02  1.821569e+03     263.006242
17    会議費  2849910.0  7.528922e+05  1.832442e+06  264576.109911
18   租税公課  1753000.0  4.631094e+05  1.127148e+06  162742.655268
19   支払報酬        0.0  0.000000e+00  0.000000e+00       0.000000
20  減価償却費  1385353.0  3.659840e+05  8.907575e+05  128611.537766
21     雑費   191552.0  5.060441e+04  1.231645e+05   17783.046835
22   為替差益        0.0  0.000000e+00  0.000000e+00       0.000000
23    雑収入    50000.0  1.320905e+04  3.214912e+04    4641.832723
24   為替差損        0.0  0.000000e+00  0.000000e+00       0.000000

In [ ]:
# 四捨五入して行う
df_PL_divide_category_goal['配賦用Biz'] = df_PL_divide_category_goal['配賦用Biz'].round()
df_PL_divide_category_goal['配賦用dev'] = df_PL_divide_category_goal['配賦用dev'].round()
df_PL_divide_category_goal['配賦用PJ'] =df_PL_divide_category_goal['PL科目金額'] - df_PL_divide_category_goal['配賦用Biz'] - df_PL_divide_category_goal['配賦用dev']

In [ ]:
df_PL_divide_category_goal

     PL科目     PL科目金額     配賦用Biz     配賦用dev     配賦用PJ
0      賞与        0.0        0.0        0.0       0.0
1   法定福利費  2266464.0   598757.0  1457296.0  210411.0
2   福利厚生費   267043.0    70548.0   171704.0   24791.0
3     採用費  1343332.0   354883.0   863739.0  124710.0
4   広告宣伝費        0.0        0.0        0.0       0.0
5    荷造運賃   536138.0   141637.0   344727.0   49774.0
6     交際費   175575.0    46384.0   112892.0   16299.0
7   旅費交通費   241439.0    63784.0   155241.0   22414.0
8     通信費   800707.0   211532.0   514840.0   74335.0
9    消耗品費  4075862.0  1076765.0  2620707.0  378390.0
10  水道光熱費   798625.0   210982.0   513502.0   74141.0
11    保険料   411113.0   108608.0   264338.0   38167.0
12    修繕費    59497.0    15718.0    38256.0    5523.0
13    研修費        0.0        0.0        0.0       0.0
14   地代家賃  8961834.0  2367547.0  5762301.0  831986.0
15  支払手数料  9971422.0  2634261.0  6411448.0  925713.0
16    諸会費     2833.0      748.0     1822.0     263.0
17    会議費  2849910.0   752892.0  1832442.0  264576.0
18   租税公課  1753000.0   463109.0  1127148.0  162743.0
19   支払報酬        0.0        0.0        0.0       0.0
20  減価償却費  1385353.0   365984.0   890757.0  128612.0
21     雑費   191552.0    50604.0   123165.0   17783.0
22   為替差益        0.0        0.0        0.0       0.0
23    雑収入    50000.0    13209.0    32149.0    4642.0
24   為替差損        0.0        0.0        0.0       0.0

In [ ]:
df_PL_divide_category_goal.to_excel('出力結果/PL配賦(biz,dev,pjに3分割).xlsx')

## biz,pj,devの縦計データ結合

In [ ]:
biz_dev_pj_concat = pd.concat([df_biz_sum,df_pj_sum,df_dev_sum],axis=0)
biz_dev_pj_concat.reset_index(inplace=True,drop=True)
biz_dev_pj_concat

                                           部門名称        出勤時間   データ種別
0                                           社長室    20.53125  配賦用biz
1                                         経営企画部   42.114583  配賦用biz
2                                         人事総務部  132.093056  配賦用biz
3                                           経理部   36.489583  配賦用biz
4                                           法務部   26.073611  配賦用biz
5                                         内部監査室    6.577778  配賦用biz
6                                        BU1営業部  218.809028  配賦用biz
7                                        BU2営業部  200.195139  配賦用biz
8                                        BU3営業部   64.934028  配賦用biz
9                                     アライアンス戦略室   95.234722  配賦用biz
10                                     マーケティング部  222.808333  配賦用biz
11                              カスタマーコミュニケーション部  349.334028  配賦用biz
12                                        品質管理部   46.390278  配賦用biz
13                                       ESG推進室   20.222222  配賦用biz
14                                      0:保守、運用  219.553472   配賦用PJ
15                        49:次世代カメラ開発(SafieOne）   41.288194   配賦用PJ
16                                      52:解析PF   33.315972   配賦用PJ
17                                     53:AIApp   55.986806   配賦用PJ
18                   61:Enterprise Toolマイグレーション    2.026389   配賦用PJ
19                                    63:在庫システム    6.379861   配賦用PJ
20                                 64:Entrance2   33.851389   配賦用PJ
21                                 65:鹿島建設DX PJ    4.261111   配賦用PJ
22                                 68:i-PRO製PTZ    9.743056   配賦用PJ
23                           69:MyPageと契約管理システム   32.171528   配賦用PJ
24                   71:Pocket2 位置情報連携など機能追加/改良     15.9125   配賦用PJ
25                          72:Safie API 組込販売改善    9.193056   配賦用PJ
26                            73:SafieManagerV3   15.360417   配賦用PJ
27                                  74:MyPortal    5.646528   配賦用PJ
28           76:(旧59)ソフトフェアPJ Mobile App (2022)   23.647917   配賦用PJ
29               77:(旧60)ソフトフェアPJ Viewer (2022)   23.445139   配賦用PJ
30  78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool   13.527778   配賦用PJ
31                     79:(旧66)ソフトフェアPJ データ分析基盤    27.83125   配賦用PJ
32                                   80:Pocket3    3.695833   配賦用PJ
33                                     81:多台数対応   15.599306   配賦用PJ
34                                  83:Pocket2+     4.31875   配賦用PJ
35                                  84:メッシュWiFi     2.75625   配賦用PJ
36                                    85:シェアプラス      3.7625   配賦用PJ
37                              86:Local Viewer    5.552778   配賦用PJ
38                                    BU1プロダクト部   25.183333  配賦用dev
39                                    BU2プロダクト部    20.95625  配賦用dev
40                                    BU3プロダクト部    8.235417  配賦用dev
41                                   プロダクト基盤開発部   73.516667  配賦用dev
42                              プラットフォームビジネス開発室    6.413889  配賦用dev
43                                     デザインセンター   61.454167  配賦用dev
44                                      業務システム部   18.190278  配賦用dev

## PL各項目を、各部門の時間の合計で割り、一単位当たりを求める

In [ ]:
#各部門時間の合計
print(df_biz_sum['出勤時間'].sum())
print(df_dev_sum['出勤時間'].sum())
print(df_pj_sum['出勤時間'].sum())

1481.8076388888887
213.95
608.827777777778

### 一単位で割る

In [ ]:
#時間計で割って一単位当たりへ変換
df_PL_divide_category_goal['一単位当たり配賦用Biz'] = df_PL_divide_category_goal['配賦用Biz'] / df_biz_sum['出勤時間'].sum()
df_PL_divide_category_goal['一単位当たり配賦用dev'] = df_PL_divide_category_goal['配賦用dev'] / df_dev_sum['出勤時間'].sum()
df_PL_divide_category_goal['一単位当たり配賦用PJ']  = df_PL_divide_category_goal['配賦用PJ']  / df_pj_sum['出勤時間'].sum()

df_PL_divide_category_goal.head()

,PL科目,PL科目金額,配賦用Biz,配賦用dev,配賦用PJ,一単位当たり配賦用Biz,一単位当たり配賦用dev,一単位当たり配賦用PJ
0,賞与,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,法定福利費,2266464.0,598757.0,1457296.0,210411.0,404.072016,6811.385838,345.600197
2,福利厚生費,267043.0,70548.0,171704.0,24791.0,47.609418,802.542650,40.719233
3,採用費,1343332.0,354883.0,863739.0,124710.0,239.493299,4037.106801,204.836252
4,広告宣伝費,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000

##biz配賦2段階目

In [ ]:
biz_unit1_sum =  df_PL_divide_category_goal['一単位当たり配賦用Biz'].sum()
biz_category_calc_list = []

for biz_name in df_biz_sum['出勤時間']:
    biz_category_sum = biz_name * biz_unit1_sum
    biz_category_calc_list.append(biz_category_sum)

df_biz_sum['配賦合計'] = biz_category_calc_list

In [ ]:
#bizをさらに配賦する
category_name_number = 0
#各PL科目の1単位分 * 各部門の出勤時間
for unit_1 in df_PL_divide_category_goal['一単位当たり配賦用Biz']:
    biz_unit_1_list = []
    #部門指定して出勤時間を掛ける
    for biz_time in df_biz_sum['出勤時間']:
        #1単位掛ける各部門
        calc_biz_unit_1 = unit_1 * biz_time
        biz_unit_1_list.append(calc_biz_unit_1)

    #bizのシート（部門名称、出勤時間、データ種別）の行方向に情報を足していく
    df_biz_sum[df_PL_divide_category_goal['PL科目'][category_name_number]] = biz_unit_1_list
    category_name_number = category_name_number+1

df_biz_sum = df_biz_sum.round()
df_biz_sum

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,社長室,20.53125,配賦用biz,132292.0,0.0,8296.0,977.0,4917.0,0.0,1962.0,...,36499.0,10.0,10432.0,6417.0,0.0,5071.0,701.0,0.0,183.0,0.0
1,経営企画部,42.114583,配賦用biz,271363.0,0.0,17017.0,2005.0,10086.0,0.0,4025.0,...,74869.0,21.0,21398.0,13162.0,0.0,10402.0,1438.0,0.0,375.0,0.0
2,人事総務部,132.093056,配賦用biz,851135.0,0.0,53375.0,6289.0,31635.0,0.0,12626.0,...,234826.0,67.0,67115.0,41283.0,0.0,32625.0,4511.0,0.0,1177.0,0.0
3,経理部,36.489583,配賦用biz,235119.0,0.0,14744.0,1737.0,8739.0,0.0,3488.0,...,64869.0,18.0,18540.0,11404.0,0.0,9012.0,1246.0,0.0,325.0,0.0
4,法務部,26.073611,配賦用biz,168004.0,0.0,10536.0,1241.0,6244.0,0.0,2492.0,...,46352.0,13.0,13248.0,8149.0,0.0,6440.0,890.0,0.0,232.0,0.0
5,内部監査室,6.577778,配賦用biz,42384.0,0.0,2658.0,313.0,1575.0,0.0,629.0,...,11694.0,3.0,3342.0,2056.0,0.0,1625.0,225.0,0.0,59.0,0.0
6,BU1営業部,218.809028,配賦用biz,1409885.0,0.0,88415.0,10417.0,52403.0,0.0,20915.0,...,388984.0,110.0,111175.0,68384.0,0.0,54043.0,7472.0,0.0,1950.0,0.0
7,BU2営業部,200.195139,配賦用biz,1289947.0,0.0,80893.0,9531.0,47945.0,0.0,19135.0,...,355894.0,101.0,101717.0,62567.0,0.0,49445.0,6837.0,0.0,1785.0,0.0
8,BU3営業部,64.934028,配賦用biz,418399.0,0.0,26238.0,3091.0,15551.0,0.0,6207.0,...,115435.0,33.0,32992.0,20294.0,0.0,16038.0,2218.0,0.0,579.0,0.0
9,アライアンス戦略室,95.234722,配賦用biz,613640.0,0.0,38482.0,4534.0,22808.0,0.0,9103.0,...,169302.0,48.0,48388.0,29764.0,0.0,23522.0,3252.0,0.0,849.0,0.0
10,マーケティング部,222.808333,配賦用biz,1435654.0,0.0,90031.0,10608.0,53361.0,0.0,21297.0,...,396094.0,112.0,113207.0,69634.0,0.0,55030.0,7609.0,0.0,1986.0,0.0
11,カスタマーコミュニケーション部,349.334028,配賦用biz,2250916.0,0.0,141156.0,16632.0,83663.0,0.0,33391.0,...,621023.0,176.0,177493.0,109177.0,0.0,86280.0,11930.0,0.0,3114.0,0.0
12,品質管理部,46.390278,配賦用biz,298913.0,0.0,18745.0,2209.0,11110.0,0.0,4434.0,...,82470.0,23.0,23570.0,14498.0,0.0,11458.0,1584.0,0.0,414.0,0.0
13,ESG推進室,20.222222,配賦用biz,130301.0,0.0,8171.0,963.0,4843.0,0.0,1933.0,...,35950.0,10.0,10275.0,6320.0,0.0,4995.0,691.0,0.0,180.0,0.0

##df_biz_sumを縦計して計算元と比較する。差額を任意の部門に足し引きする。

In [ ]:
#計算スペースを取得して、差を計算
df_biz_sum_calc_fraction = df_biz_sum.drop(['部門名称','出勤時間','データ種別','配賦合計'],axis=1)
calc_fraction = df_biz_sum.drop(['部門名称','出勤時間','データ種別','配賦合計'],axis=1).sum(axis=0)
calc_fraction = list(calc_fraction)
calc_fraction = df_PL_divide_category_goal['配賦用Biz'] - calc_fraction
#calc_fraction

#一番上の行で、足し引き算する
df_biz_change_fraction = list(df_biz_sum_calc_fraction.loc[0]) - calc_fraction
df_biz_sum_calc_fraction.loc[0] = list(df_biz_change_fraction)
df_biz_sum_calc_fraction

,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,交際費,旅費交通費,通信費,消耗品費,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,0.0,8296.0,976.0,4914.0,0.0,1962.0,643.0,884.0,2931.0,14920.0,...,36499.0,7.0,10432.0,6417.0,0.0,5073.0,701.0,0.0,182.0,0.0
1,0.0,17017.0,2005.0,10086.0,0.0,4025.0,1318.0,1813.0,6012.0,30603.0,...,74869.0,21.0,21398.0,13162.0,0.0,10402.0,1438.0,0.0,375.0,0.0
2,0.0,53375.0,6289.0,31635.0,0.0,12626.0,4135.0,5686.0,18857.0,95986.0,...,234826.0,67.0,67115.0,41283.0,0.0,32625.0,4511.0,0.0,1177.0,0.0
3,0.0,14744.0,1737.0,8739.0,0.0,3488.0,1142.0,1571.0,5209.0,26515.0,...,64869.0,18.0,18540.0,11404.0,0.0,9012.0,1246.0,0.0,325.0,0.0
4,0.0,10536.0,1241.0,6244.0,0.0,2492.0,816.0,1122.0,3722.0,18947.0,...,46352.0,13.0,13248.0,8149.0,0.0,6440.0,890.0,0.0,232.0,0.0
5,0.0,2658.0,313.0,1575.0,0.0,629.0,206.0,283.0,939.0,4780.0,...,11694.0,3.0,3342.0,2056.0,0.0,1625.0,225.0,0.0,59.0,0.0
6,0.0,88415.0,10417.0,52403.0,0.0,20915.0,6849.0,9419.0,31236.0,158999.0,...,388984.0,110.0,111175.0,68384.0,0.0,54043.0,7472.0,0.0,1950.0,0.0
7,0.0,80893.0,9531.0,47945.0,0.0,19135.0,6267.0,8617.0,28578.0,145473.0,...,355894.0,101.0,101717.0,62567.0,0.0,49445.0,6837.0,0.0,1785.0,0.0
8,0.0,26238.0,3091.0,15551.0,0.0,6207.0,2033.0,2795.0,9270.0,47185.0,...,115435.0,33.0,32992.0,20294.0,0.0,16038.0,2218.0,0.0,579.0,0.0
9,0.0,38482.0,4534.0,22808.0,0.0,9103.0,2981.0,4099.0,13595.0,69203.0,...,169302.0,48.0,48388.0,29764.0,0.0,23522.0,3252.0,0.0,849.0,0.0
10,0.0,90031.0,10608.0,53361.0,0.0,21297.0,6974.0,9591.0,31806.0,161905.0,...,396094.0,112.0,113207.0,69634.0,0.0,55030.0,7609.0,0.0,1986.0,0.0
11,0.0,141156.0,16632.0,83663.0,0.0,33391.0,10935.0,15037.0,49868.0,253846.0,...,621023.0,176.0,177493.0,109177.0,0.0,86280.0,11930.0,0.0,3114.0,0.0
12,0.0,18745.0,2209.0,11110.0,0.0,4434.0,1452.0,1997.0,6622.0,33710.0,...,82470.0,23.0,23570.0,14498.0,0.0,11458.0,1584.0,0.0,414.0,0.0
13,0.0,8171.0,963.0,4843.0,0.0,1933.0,633.0,870.0,2887.0,14695.0,...,35950.0,10.0,10275.0,6320.0,0.0,4995.0,691.0,0.0,180.0,0.0

In [ ]:
#加工後（端数処理後）データと計算のため切り離した['部門名称','出勤時間','データ種別','配賦合計']を結合する
df_biz_sum = pd.concat([df_biz_sum[['部門名称','出勤時間','データ種別','配賦合計']],df_biz_sum_calc_fraction],axis=1)

df_biz_sum

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,社長室,20.53125,配賦用biz,132292.0,0.0,8296.0,976.0,4914.0,0.0,1962.0,...,36499.0,7.0,10432.0,6417.0,0.0,5073.0,701.0,0.0,182.0,0.0
1,経営企画部,42.114583,配賦用biz,271363.0,0.0,17017.0,2005.0,10086.0,0.0,4025.0,...,74869.0,21.0,21398.0,13162.0,0.0,10402.0,1438.0,0.0,375.0,0.0
2,人事総務部,132.093056,配賦用biz,851135.0,0.0,53375.0,6289.0,31635.0,0.0,12626.0,...,234826.0,67.0,67115.0,41283.0,0.0,32625.0,4511.0,0.0,1177.0,0.0
3,経理部,36.489583,配賦用biz,235119.0,0.0,14744.0,1737.0,8739.0,0.0,3488.0,...,64869.0,18.0,18540.0,11404.0,0.0,9012.0,1246.0,0.0,325.0,0.0
4,法務部,26.073611,配賦用biz,168004.0,0.0,10536.0,1241.0,6244.0,0.0,2492.0,...,46352.0,13.0,13248.0,8149.0,0.0,6440.0,890.0,0.0,232.0,0.0
5,内部監査室,6.577778,配賦用biz,42384.0,0.0,2658.0,313.0,1575.0,0.0,629.0,...,11694.0,3.0,3342.0,2056.0,0.0,1625.0,225.0,0.0,59.0,0.0
6,BU1営業部,218.809028,配賦用biz,1409885.0,0.0,88415.0,10417.0,52403.0,0.0,20915.0,...,388984.0,110.0,111175.0,68384.0,0.0,54043.0,7472.0,0.0,1950.0,0.0
7,BU2営業部,200.195139,配賦用biz,1289947.0,0.0,80893.0,9531.0,47945.0,0.0,19135.0,...,355894.0,101.0,101717.0,62567.0,0.0,49445.0,6837.0,0.0,1785.0,0.0
8,BU3営業部,64.934028,配賦用biz,418399.0,0.0,26238.0,3091.0,15551.0,0.0,6207.0,...,115435.0,33.0,32992.0,20294.0,0.0,16038.0,2218.0,0.0,579.0,0.0
9,アライアンス戦略室,95.234722,配賦用biz,613640.0,0.0,38482.0,4534.0,22808.0,0.0,9103.0,...,169302.0,48.0,48388.0,29764.0,0.0,23522.0,3252.0,0.0,849.0,0.0
10,マーケティング部,222.808333,配賦用biz,1435654.0,0.0,90031.0,10608.0,53361.0,0.0,21297.0,...,396094.0,112.0,113207.0,69634.0,0.0,55030.0,7609.0,0.0,1986.0,0.0
11,カスタマーコミュニケーション部,349.334028,配賦用biz,2250916.0,0.0,141156.0,16632.0,83663.0,0.0,33391.0,...,621023.0,176.0,177493.0,109177.0,0.0,86280.0,11930.0,0.0,3114.0,0.0
12,品質管理部,46.390278,配賦用biz,298913.0,0.0,18745.0,2209.0,11110.0,0.0,4434.0,...,82470.0,23.0,23570.0,14498.0,0.0,11458.0,1584.0,0.0,414.0,0.0
13,ESG推進室,20.222222,配賦用biz,130301.0,0.0,8171.0,963.0,4843.0,0.0,1933.0,...,35950.0,10.0,10275.0,6320.0,0.0,4995.0,691.0,0.0,180.0,0.0

## dev配賦2段階目

In [ ]:
#各部門にPLの配賦用dev合計して配賦（端数処理のため）
dev_unit1_sum =  df_PL_divide_category_goal['一単位当たり配賦用dev'].sum()
dev_category_calc_list = []

for dev_name in df_dev_sum['出勤時間']:
    dev_category_sum = dev_name * dev_unit1_sum
    dev_category_calc_list.append(dev_category_sum)

df_dev_sum['配賦合計'] = dev_category_calc_list

In [ ]:
#devをさらに配賦する
category_name_number = 0
#各PL科目の1単位分 * 各部門の出勤時間
for unit_1 in df_PL_divide_category_goal['一単位当たり配賦用dev']:
    dev_unit_1_list = []
    #部門指定して出勤時間を掛ける
    for dev_time in df_dev_sum['出勤時間']:
        #1単位掛ける各部門
        calc_dev_unit_1 = unit_1 * dev_time
        dev_unit_1_list.append(calc_dev_unit_1)

    #devのシート（部門名称、出勤時間、データ種別）の行方向に情報を足していく
    df_dev_sum[df_PL_divide_category_goal['PL科目'][category_name_number]] = dev_unit_1_list
    category_name_number = category_name_number+1

df_dev_sum = df_dev_sum.round()

df_dev_sum.head()

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,BU1プロダクト部,25.183333,配賦用dev,2735322.0,0.0,171533.0,20211.0,101668.0,0.0,40577.0,...,754670.0,214.0,215691.0,132673.0,0.0,104848.0,14497.0,0.0,3784.0,0.0
1,BU2プロダクト部,20.95625,配賦用dev,2276192.0,0.0,142741.0,16818.0,84603.0,0.0,33766.0,...,627997.0,178.0,179486.0,110403.0,0.0,87249.0,12064.0,0.0,3149.0,0.0
2,BU3プロダクト部,8.235417,配賦用dev,894501.0,0.0,56095.0,6609.0,33247.0,0.0,13269.0,...,246791.0,70.0,70535.0,43386.0,0.0,34287.0,4741.0,0.0,1237.0,0.0
3,プロダクト基盤開発部,73.516667,配賦用dev,7985114.0,0.0,500750.0,59000.0,296795.0,0.0,118454.0,...,2203077.0,626.0,629657.0,387306.0,0.0,306078.0,42321.0,0.0,11047.0,0.0
4,プラットフォームビジネス開発室,6.413889,配賦用dev,696653.0,0.0,43687.0,5147.0,25894.0,0.0,10334.0,...,192205.0,55.0,54934.0,33790.0,0.0,26704.0,3692.0,0.0,964.0,0.0

In [ ]:
#計算スペースを取得して、差を計算
df_dev_sum_calc_fraction = df_dev_sum.drop(['部門名称','出勤時間','データ種別','配賦合計'],axis=1)
calc_fraction = df_dev_sum.drop(['部門名称','出勤時間','データ種別','配賦合計'],axis=1).sum(axis=0)
calc_fraction = list(calc_fraction)
calc_fraction = df_PL_divide_category_goal['配賦用dev'] - calc_fraction
#calc_fraction

#一番上の行で、足し引き算する
df_dev_change_fraction = list(df_dev_sum_calc_fraction.loc[0]) - calc_fraction
df_dev_sum_calc_fraction.loc[0] = list(df_dev_change_fraction)
df_dev_sum_calc_fraction

,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,交際費,旅費交通費,通信費,消耗品費,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,0.0,171532.0,20210.0,101669.0,0.0,40577.0,13288.0,18274.0,60599.0,308476.0,...,754670.0,213.0,215692.0,132672.0,0.0,104848.0,14496.0,0.0,3783.0,0.0
1,0.0,142741.0,16818.0,84603.0,0.0,33766.0,11058.0,15206.0,50428.0,256696.0,...,627997.0,178.0,179486.0,110403.0,0.0,87249.0,12064.0,0.0,3149.0,0.0
2,0.0,56095.0,6609.0,33247.0,0.0,13269.0,4345.0,5976.0,19817.0,100877.0,...,246791.0,70.0,70535.0,43386.0,0.0,34287.0,4741.0,0.0,1237.0,0.0
3,0.0,500750.0,59000.0,296795.0,0.0,118454.0,38792.0,53343.0,176907.0,900517.0,...,2203077.0,626.0,629657.0,387306.0,0.0,306078.0,42321.0,0.0,11047.0,0.0
4,0.0,43687.0,5147.0,25894.0,0.0,10334.0,3384.0,4654.0,15434.0,78565.0,...,192205.0,55.0,54934.0,33790.0,0.0,26704.0,3692.0,0.0,964.0,0.0
5,0.0,418588.0,49320.0,248097.0,0.0,99018.0,32427.0,44591.0,147881.0,752762.0,...,1841599.0,523.0,526344.0,323758.0,0.0,255858.0,35377.0,0.0,9234.0,0.0
6,0.0,123901.0,14598.0,73436.0,0.0,29309.0,9598.0,13199.0,43772.0,222816.0,...,545109.0,155.0,155796.0,95831.0,0.0,75733.0,10472.0,0.0,2733.0,0.0

In [ ]:
#加工後（端数処理後）データと計算のため切り離した['部門名称','出勤時間','データ種別','配賦合計']を結合する
df_dev_sum = pd.concat([df_dev_sum[['部門名称','出勤時間','データ種別','配賦合計']],df_dev_sum_calc_fraction],axis=1)

df_dev_sum

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,BU1プロダクト部,25.183333,配賦用dev,2735322.0,0.0,171532.0,20210.0,101669.0,0.0,40577.0,...,754670.0,213.0,215692.0,132672.0,0.0,104848.0,14496.0,0.0,3783.0,0.0
1,BU2プロダクト部,20.95625,配賦用dev,2276192.0,0.0,142741.0,16818.0,84603.0,0.0,33766.0,...,627997.0,178.0,179486.0,110403.0,0.0,87249.0,12064.0,0.0,3149.0,0.0
2,BU3プロダクト部,8.235417,配賦用dev,894501.0,0.0,56095.0,6609.0,33247.0,0.0,13269.0,...,246791.0,70.0,70535.0,43386.0,0.0,34287.0,4741.0,0.0,1237.0,0.0
3,プロダクト基盤開発部,73.516667,配賦用dev,7985114.0,0.0,500750.0,59000.0,296795.0,0.0,118454.0,...,2203077.0,626.0,629657.0,387306.0,0.0,306078.0,42321.0,0.0,11047.0,0.0
4,プラットフォームビジネス開発室,6.413889,配賦用dev,696653.0,0.0,43687.0,5147.0,25894.0,0.0,10334.0,...,192205.0,55.0,54934.0,33790.0,0.0,26704.0,3692.0,0.0,964.0,0.0
5,デザインセンター,61.454167,配賦用dev,6674929.0,0.0,418588.0,49320.0,248097.0,0.0,99018.0,...,1841599.0,523.0,526344.0,323758.0,0.0,255858.0,35377.0,0.0,9234.0,0.0
6,業務システム部,18.190278,配賦用dev,1975762.0,0.0,123901.0,14598.0,73436.0,0.0,29309.0,...,545109.0,155.0,155796.0,95831.0,0.0,75733.0,10472.0,0.0,2733.0,0.0

## pj配賦二段階目

In [ ]:
#各部門にPLの配賦用Biz合計して配賦（端数処理のため）
pj_unit1_sum =  df_PL_divide_category_goal['一単位当たり配賦用PJ'].sum()
pj_category_calc_list = []

for pj_name in df_pj_sum['出勤時間']:
    pj_category_sum = pj_name * pj_unit1_sum
    pj_category_calc_list.append(pj_category_sum)

df_pj_sum['配賦合計'] = pj_category_calc_list

In [ ]:
#pjをさらに配賦する
category_name_number = 0
#各PL科目の1単位分 * 各部門の出勤時間
for unit_1 in df_PL_divide_category_goal['一単位当たり配賦用PJ']:
    pj_unit_1_list = []
    #部門指定して出勤時間を掛ける
    for pj_time in df_pj_sum['出勤時間']:
        #1単位掛ける各部門
        calc_pj_unit_1 = unit_1 * pj_time
        pj_unit_1_list.append(calc_pj_unit_1)

    #bizのシート（部門名称、出勤時間、データ種別）の行方向に情報を足していく
    df_pj_sum[df_PL_divide_category_goal['PL科目'][category_name_number]] = pj_unit_1_list
    category_name_number = category_name_number+1

df_pj_sum = df_pj_sum.round()
df_pj_sum.head()

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,0:保守、運用,219.553472,配賦用PJ,1209968.0,0.0,75878.0,8940.0,44973.0,0.0,17949.0,...,333828.0,95.0,95411.0,58688.0,0.0,46380.0,6413.0,0.0,1674.0,0.0
1,49:次世代カメラ開発(SafieOne）,41.288194,配賦用PJ,227541.0,0.0,14269.0,1681.0,8457.0,0.0,3375.0,...,62778.0,18.0,17942.0,11037.0,0.0,8722.0,1206.0,0.0,315.0,0.0
2,52:解析PF,33.315972,配賦用PJ,183606.0,0.0,11514.0,1357.0,6824.0,0.0,2724.0,...,50656.0,14.0,14478.0,8906.0,0.0,7038.0,973.0,0.0,254.0,0.0
3,53:AIApp,55.986806,配賦用PJ,308545.0,0.0,19349.0,2280.0,11468.0,0.0,4577.0,...,85127.0,24.0,24330.0,14966.0,0.0,11827.0,1635.0,0.0,427.0,0.0
4,61:Enterprise Toolマイグレーション,2.026389,配賦用PJ,11168.0,0.0,700.0,83.0,415.0,0.0,166.0,...,3081.0,1.0,881.0,542.0,0.0,428.0,59.0,0.0,15.0,0.0

In [ ]:
#計算スペースを取得して、差を計算
df_pj_sum_calc_fraction = df_pj_sum.drop(['部門名称','出勤時間','データ種別','配賦合計'],axis=1)
calc_fraction = df_pj_sum.drop(['部門名称','出勤時間','データ種別','配賦合計'],axis=1).sum(axis=0)
calc_fraction = list(calc_fraction)
calc_fraction = df_PL_divide_category_goal['配賦用PJ'] - calc_fraction
#calc_fraction

#一番上の行で、足し引き算する
df_pj_change_fraction = list(df_pj_sum_calc_fraction.loc[0]) - calc_fraction
df_pj_sum_calc_fraction.loc[0] = list(df_pj_change_fraction)
df_pj_sum_calc_fraction

,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,交際費,旅費交通費,通信費,消耗品費,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,0.0,75877.0,8940.0,44973.0,0.0,17949.0,5879.0,8083.0,26805.0,136453.0,...,333827.0,96.0,95413.0,58688.0,0.0,46381.0,6415.0,0.0,1672.0,0.0
1,0.0,14269.0,1681.0,8457.0,0.0,3375.0,1105.0,1520.0,5041.0,25661.0,...,62778.0,18.0,17942.0,11037.0,0.0,8722.0,1206.0,0.0,315.0,0.0
2,0.0,11514.0,1357.0,6824.0,0.0,2724.0,892.0,1227.0,4068.0,20706.0,...,50656.0,14.0,14478.0,8906.0,0.0,7038.0,973.0,0.0,254.0,0.0
3,0.0,19349.0,2280.0,11468.0,0.0,4577.0,1499.0,2061.0,6836.0,34796.0,...,85127.0,24.0,24330.0,14966.0,0.0,11827.0,1635.0,0.0,427.0,0.0
4,0.0,700.0,83.0,415.0,0.0,166.0,54.0,75.0,247.0,1259.0,...,3081.0,1.0,881.0,542.0,0.0,428.0,59.0,0.0,15.0,0.0
5,0.0,2205.0,260.0,1307.0,0.0,522.0,171.0,235.0,779.0,3965.0,...,9700.0,3.0,2772.0,1705.0,0.0,1348.0,186.0,0.0,49.0,0.0
6,0.0,11699.0,1378.0,6934.0,0.0,2767.0,906.0,1246.0,4133.0,21039.0,...,51471.0,15.0,14711.0,9049.0,0.0,7151.0,989.0,0.0,258.0,0.0
7,0.0,1473.0,174.0,873.0,0.0,348.0,114.0,157.0,520.0,2648.0,...,6479.0,2.0,1852.0,1139.0,0.0,900.0,124.0,0.0,32.0,0.0
8,0.0,3367.0,397.0,1996.0,0.0,797.0,261.0,359.0,1190.0,6055.0,...,14814.0,4.0,4234.0,2604.0,0.0,2058.0,285.0,0.0,74.0,0.0
9,0.0,11118.0,1310.0,6590.0,0.0,2630.0,861.0,1184.0,3928.0,19995.0,...,48916.0,14.0,13981.0,8600.0,0.0,6796.0,940.0,0.0,245.0,0.0
10,0.0,5499.0,648.0,3259.0,0.0,1301.0,426.0,586.0,1943.0,9890.0,...,24195.0,7.0,6915.0,4253.0,0.0,3361.0,465.0,0.0,121.0,0.0
11,0.0,3177.0,374.0,1883.0,0.0,752.0,246.0,338.0,1122.0,5714.0,...,13978.0,4.0,3995.0,2457.0,0.0,1942.0,269.0,0.0,70.0,0.0
12,0.0,5309.0,625.0,3146.0,0.0,1256.0,411.0,565.0,1875.0,9547.0,...,23355.0,7.0,6675.0,4106.0,0.0,3245.0,449.0,0.0,117.0,0.0
13,0.0,1951.0,230.0,1157.0,0.0,462.0,151.0,208.0,689.0,3509.0,...,8585.0,2.0,2454.0,1509.0,0.0,1193.0,165.0,0.0,43.0,0.0
14,0.0,8173.0,963.0,4844.0,0.0,1933.0,633.0,871.0,2887.0,14697.0,...,35956.0,10.0,10277.0,6321.0,0.0,4996.0,691.0,0.0,180.0,0.0
15,0.0,8103.0,955.0,4802.0,0.0,1917.0,628.0,863.0,2863.0,14571.0,...,35648.0,10.0,10188.0,6267.0,0.0,4953.0,685.0,0.0,179.0,0.0
16,0.0,4675.0,551.0,2771.0,0.0,1106.0,362.0,498.0,1652.0,8408.0,...,20569.0,6.0,5879.0,3616.0,0.0,2858.0,395.0,0.0,103.0,0.0
17,0.0,9618.0,1133.0,5701.0,0.0,2275.0,745.0,1025.0,3398.0,17297.0,...,42317.0,12.0,12095.0,7439.0,0.0,5879.0,813.0,0.0,212.0,0.0
18,0.0,1277.0,150.0,757.0,0.0,302.0,99.0,136.0,451.0,2297.0,...,5619.0,2.0,1606.0,988.0,0.0,781.0,108.0,0.0,28.0,0.0
19,0.0,5391.0,635.0,3195.0,0.0,1275.0,418.0,574.0,1905.0,9695.0,...,23718.0,7.0,6779.0,4170.0,0.0,3295.0,456.0,0.0,119.0,0.0
20,0.0,1493.0,176.0,885.0,0.0,353.0,116.0,159.0,527.0,2684.0,...,6567.0,2.0,1877.0,1154.0,0.0,912.0,126.0,0.0,33.0,0.0
21,0.0,953.0,112.0,565.0,0.0,225.0,74.0,101.0,337.0,1713.0,...,4191.0,1.0,1198.0,737.0,0.0,582.0,81.0,0.0,21.0,0.0
22,0.0,1300.0,153.0,771.0,0.0,308.0,101.0,139.0,459.0,2338.0,...,5721.0,2.0,1635.0,1006.0,0.0,795.0,110.0,0.0,29.0,0.0
23,0.0,1919.0,226.0,1137.0,0.0,454.0,149.0,204.0,678.0,3451.0,...,8443.0,2.0,2413.0,1484.0,0.0,1173.0,162.0,0.0,42.0,0.0

In [ ]:
#加工後（端数処理後）データと計算のため切り離した['部門名称','出勤時間','データ種別','配賦合計']を結合する
df_pj_sum = pd.concat([df_pj_sum[['部門名称','出勤時間','データ種別','配賦合計']],df_pj_sum_calc_fraction],axis=1)

df_pj_sum

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,0:保守、運用,219.553472,配賦用PJ,1209968.0,0.0,75877.0,8940.0,44973.0,0.0,17949.0,...,333827.0,96.0,95413.0,58688.0,0.0,46381.0,6415.0,0.0,1672.0,0.0
1,49:次世代カメラ開発(SafieOne）,41.288194,配賦用PJ,227541.0,0.0,14269.0,1681.0,8457.0,0.0,3375.0,...,62778.0,18.0,17942.0,11037.0,0.0,8722.0,1206.0,0.0,315.0,0.0
2,52:解析PF,33.315972,配賦用PJ,183606.0,0.0,11514.0,1357.0,6824.0,0.0,2724.0,...,50656.0,14.0,14478.0,8906.0,0.0,7038.0,973.0,0.0,254.0,0.0
3,53:AIApp,55.986806,配賦用PJ,308545.0,0.0,19349.0,2280.0,11468.0,0.0,4577.0,...,85127.0,24.0,24330.0,14966.0,0.0,11827.0,1635.0,0.0,427.0,0.0
4,61:Enterprise Toolマイグレーション,2.026389,配賦用PJ,11168.0,0.0,700.0,83.0,415.0,0.0,166.0,...,3081.0,1.0,881.0,542.0,0.0,428.0,59.0,0.0,15.0,0.0
5,63:在庫システム,6.379861,配賦用PJ,35160.0,0.0,2205.0,260.0,1307.0,0.0,522.0,...,9700.0,3.0,2772.0,1705.0,0.0,1348.0,186.0,0.0,49.0,0.0
6,64:Entrance2,33.851389,配賦用PJ,186556.0,0.0,11699.0,1378.0,6934.0,0.0,2767.0,...,51471.0,15.0,14711.0,9049.0,0.0,7151.0,989.0,0.0,258.0,0.0
7,65:鹿島建設DX PJ,4.261111,配賦用PJ,23483.0,0.0,1473.0,174.0,873.0,0.0,348.0,...,6479.0,2.0,1852.0,1139.0,0.0,900.0,124.0,0.0,32.0,0.0
8,68:i-PRO製PTZ,9.743056,配賦用PJ,53694.0,0.0,3367.0,397.0,1996.0,0.0,797.0,...,14814.0,4.0,4234.0,2604.0,0.0,2058.0,285.0,0.0,74.0,0.0
9,69:MyPageと契約管理システム,32.171528,配賦用PJ,177299.0,0.0,11118.0,1310.0,6590.0,0.0,2630.0,...,48916.0,14.0,13981.0,8600.0,0.0,6796.0,940.0,0.0,245.0,0.0
10,71:Pocket2 位置情報連携など機能追加/改良,15.9125,配賦用PJ,87694.0,0.0,5499.0,648.0,3259.0,0.0,1301.0,...,24195.0,7.0,6915.0,4253.0,0.0,3361.0,465.0,0.0,121.0,0.0
11,72:Safie API 組込販売改善,9.193056,配賦用PJ,50663.0,0.0,3177.0,374.0,1883.0,0.0,752.0,...,13978.0,4.0,3995.0,2457.0,0.0,1942.0,269.0,0.0,70.0,0.0
12,73:SafieManagerV3,15.360417,配賦用PJ,84652.0,0.0,5309.0,625.0,3146.0,0.0,1256.0,...,23355.0,7.0,6675.0,4106.0,0.0,3245.0,449.0,0.0,117.0,0.0
13,74:MyPortal,5.646528,配賦用PJ,31118.0,0.0,1951.0,230.0,1157.0,0.0,462.0,...,8585.0,2.0,2454.0,1509.0,0.0,1193.0,165.0,0.0,43.0,0.0
14,76:(旧59)ソフトフェアPJ Mobile App (2022),23.647917,配賦用PJ,130325.0,0.0,8173.0,963.0,4844.0,0.0,1933.0,...,35956.0,10.0,10277.0,6321.0,0.0,4996.0,691.0,0.0,180.0,0.0
15,77:(旧60)ソフトフェアPJ Viewer (2022),23.445139,配賦用PJ,129207.0,0.0,8103.0,955.0,4802.0,0.0,1917.0,...,35648.0,10.0,10188.0,6267.0,0.0,4953.0,685.0,0.0,179.0,0.0
16,78:(旧62ソフトフェアPJ 代理店対応)⇒ソフトフェアPJ Agency Tool,13.527778,配賦用PJ,74552.0,0.0,4675.0,551.0,2771.0,0.0,1106.0,...,20569.0,6.0,5879.0,3616.0,0.0,2858.0,395.0,0.0,103.0,0.0
17,79:(旧66)ソフトフェアPJ データ分析基盤,27.83125,配賦用PJ,153379.0,0.0,9618.0,1133.0,5701.0,0.0,2275.0,...,42317.0,12.0,12095.0,7439.0,0.0,5879.0,813.0,0.0,212.0,0.0
18,80:Pocket3,3.695833,配賦用PJ,20368.0,0.0,1277.0,150.0,757.0,0.0,302.0,...,5619.0,2.0,1606.0,988.0,0.0,781.0,108.0,0.0,28.0,0.0
19,81:多台数対応,15.599306,配賦用PJ,85968.0,0.0,5391.0,635.0,3195.0,0.0,1275.0,...,23718.0,7.0,6779.0,4170.0,0.0,3295.0,456.0,0.0,119.0,0.0
20,83:Pocket2+,4.31875,配賦用PJ,23801.0,0.0,1493.0,176.0,885.0,0.0,353.0,...,6567.0,2.0,1877.0,1154.0,0.0,912.0,126.0,0.0,33.0,0.0
21,84:メッシュWiFi,2.75625,配賦用PJ,15190.0,0.0,953.0,112.0,565.0,0.0,225.0,...,4191.0,1.0,1198.0,737.0,0.0,582.0,81.0,0.0,21.0,0.0
22,85:シェアプラス,3.7625,配賦用PJ,20735.0,0.0,1300.0,153.0,771.0,0.0,308.0,...,5721.0,2.0,1635.0,1006.0,0.0,795.0,110.0,0.0,29.0,0.0
23,86:Local Viewer,5.552778,配賦用PJ,30602.0,0.0,1919.0,226.0,1137.0,0.0,454.0,...,8443.0,2.0,2413.0,1484.0,0.0,1173.0,162.0,0.0,42.0,0.0

In [ ]:
allocation2_concat = pd.concat([df_biz_sum,df_dev_sum,df_pj_sum])
allocation2_concat.head()

,部門名称,出勤時間,データ種別,配賦合計,賞与,法定福利費,福利厚生費,採用費,広告宣伝費,荷造運賃,...,支払手数料,諸会費,会議費,租税公課,支払報酬,減価償却費,雑費,為替差益,雑収入,為替差損
0,社長室,20.53125,配賦用biz,132292.0,0.0,8296.0,976.0,4914.0,0.0,1962.0,...,36499.0,7.0,10432.0,6417.0,0.0,5073.0,701.0,0.0,182.0,0.0
1,経営企画部,42.114583,配賦用biz,271363.0,0.0,17017.0,2005.0,10086.0,0.0,4025.0,...,74869.0,21.0,21398.0,13162.0,0.0,10402.0,1438.0,0.0,375.0,0.0
2,人事総務部,132.093056,配賦用biz,851135.0,0.0,53375.0,6289.0,31635.0,0.0,12626.0,...,234826.0,67.0,67115.0,41283.0,0.0,32625.0,4511.0,0.0,1177.0,0.0
3,経理部,36.489583,配賦用biz,235119.0,0.0,14744.0,1737.0,8739.0,0.0,3488.0,...,64869.0,18.0,18540.0,11404.0,0.0,9012.0,1246.0,0.0,325.0,0.0
4,法務部,26.073611,配賦用biz,168004.0,0.0,10536.0,1241.0,6244.0,0.0,2492.0,...,46352.0,13.0,13248.0,8149.0,0.0,6440.0,890.0,0.0,232.0,0.0

##四捨五入して、端数処理を行う
- どこかで「全体」-「なにか一つを抜いた合計」をする

In [ ]:
#為替差損だけを除いた合計値を出す(端数計算のため)
#calc_fraction = allocation2_concat.drop(['部門名称','出勤時間','データ種別','配賦合計','為替差損'],axis=1)
#calc_fraction = calc_fraction.sum(axis=1)

#calc_fraction

In [ ]:
#allocation2_concat['為替差損'] = allocation2_concat['配賦合計'] - calc_fraction
#allocation2_concat

## データ保存

In [ ]:
emploee_excel_read = pd.read_excel(employee_excel)
kintai_excel_read = pd.read_excel(kintai_excel)
kousu_excel_read = pd.read_excel(kousu_excel)
master_excel_read = pd.read_excel(master_excel)
PL_excel_read = pd.read_excel(PL_excel)

In [ ]:
with pd.ExcelWriter("最終成果物/勤務時間_PL配賦データ.xlsx") as writer:
    allocation2_concat.to_excel(writer, sheet_name='勤務時間縦計')
    df_PL_divide_category_goal.to_excel(writer, sheet_name='PL配賦')
    emploee_excel_read.to_excel(writer,sheet_name = '従業員一覧')
    kintai_excel_read.to_excel(writer,sheet_name = '個人コード順貼付データ')
    kousu_excel_read.to_excel(writer,sheet_name = '開発工数シート')
    master.to_excel(writer,sheet_name = 'マスタ')
    PL_excel_read.to_excel(writer,sheet_name = 'PL')